
flowchart TB
    subgraph Collector[OpenTelemetry Collector]
        OTLPRecv[Receiver: otlp]
        Processor1[Processor: enrichment]
        Processor2[Processor: transform]
        ElasticExporter[Exporter: Elasticsearch]
        OTLPRecv ==> Processor1 ==> Processor2 ==> ElasticExporter
    end

    subgraph Service1[service]
        subgraph LoggingFramework[Logging Framework]
            LAPI[log API]
            LAPI == message ==> OtlpExporter[Appender: otlp]
        end

        OTELSDK[OTel SDK]
        OTELSDK -. traceid,baggage .-> OtlpExporter
        func[code] == "log(message)" ==> LAPI
        func -. span .-> OTELSDK
  

        OtlpExporter == "log / otlp" ==> OTLPRecv
        OTELSDK == "span / otlp" ==> OTLPRecv
    end

    ElasticExporter == "log / http" ==> nodeId(((Elasticsearch)))
